# Generated by Django 4.2.3 on 2023-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
