# Generated by Django 4.2.3 on 2023-07-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_event_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
