# Generated by Django 4.2.3 on 2023-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_event_text_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('Groceries', 'Groceries'), ('Rent', 'Rent'), ('Taxes', 'Taxes'), ('Other', 'Other')], default='Other', max_length=10)),
            ],
        ),
    ]
